### ISSUE TITLE
Production is not picked up

### ISSUE THREAD

**Issue by Firesphere** [jonom/silverstripe-environment-awareness#2]
![image](https://user-images.githubusercontent.com/680570/229328242-05e77888-434a-403c-8782-273cd7478e13.png)
Production does not show what's in the YML

**Comment by jonom** [comment]
Might be that existing name spacing issue. Can you try removing the “JonoM\” part in your yml?

**Comment by jonom** [comment]
Example:

```
---
Name: envawareness
---
EnvironmentAwareness:
  environments:
    Local:
      short_label: "DEV"
      color: "#f26522"
      description: "Local development site"
```

![image](https://user-images.githubusercontent.com/1079425/230193967-cc184fbe-053a-4511-8720-575236e339e5.png)
![image](https://user-images.githubusercontent.com/1079425/230194566-36ed558d-c1d1-4400-ae70-46a8c9bf078a.png)

**Comment by Firesphere** [comment]
It seems to have magically picked up things now, but I'll have a closer look, maybe over the long weekend :)

**Comment by Firesphere** [comment]
It seems to have something to do with the hosting not always flushing the cache properly, but mounting it, after a build.

Problem exists between hosting and me :)
