### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Firesphere** [jonom/silverstripe-environment-awareness#4]
Would be nice.
Maybe include dependency on SS <=7 on it while at it?

**Comment by jonom** [comment]
I need to fix [this issue](SS_ENVIRONMENT_LABEL) first. Any chance you want to do that? 😁 No worries if not, I'll get around to it some day

**Comment by Firesphere** [comment]
You mean this one?
https://github.com/jonom/silverstripe-environment-awareness/issues/1

Yeah, might have a look this arvo if I have time

**Comment by jonom** [comment]
Whoops, yep that's the one

**Comment by Firesphere** [comment]
FTFY:
https://github.com/jonom/silverstripe-environment-awareness/pull/6
